### ISSUE TITLE
error while obtaining BNB BEP2 transactions

### ISSUE THREAD

**Issue by art-lucas** [zelcash/link.zel.network#1]
I'm not sure whether this is the right place to post this. I'm running Zelcore on Ubuntu 20.04, Zelcore last version, i.e., v4.15.0 Solana Summer. I've sent a low amount of BNB (BNB BEP2) from a Crypto.com wallet to Zelcore (address starting with bnb1udde). On Crypto.com, the translation is successful. On Zelcore, I keep getitng the message "error while obtaining BNB BEP2 transactions". Could you tell me what's happening and how to fix that? Or, can I recall the money if it isn't working?

**Comment by TheTrunk** [comment]
Hi @art-lucas 
The best place to open an issue is in Zelcore organisation here:
https://github.com/ZelCore-io/Zelcore

`"error while obtaining BNB BEP2 transactions"`
indicates a networking issue, that a server from which zelcore is getting transactions for BNB network (standard Binance Chain) did not supply correct data.

Zelcore backend servers can be fully adjusted directly by user in settings menu. Going to Settings -> Backend and choosing appropriate backend for a specific coin may resolve the issue. Additionally Zelcore has automatic fallbacks in infrastructure, so it goes through its known backends and tries them one by one in case a fail of getting data occures, so an error is shown only if all known backends fail.

Since we do not have any additional reports on the matter and our tests and stats run fine, it implicates that this is more user oriented issue or restriction of access to a service on backend provider side.

Many countries has restricted access to cryptocurrencies and so internet providers do not allow a connection to certain servers. For that Zelcore has built in proxy servers. You can select a proxy server in settings of Zelcore or at login screen as well. This resolve 99% of users.

**Comment by art-lucas** [comment]
Hi @TheTrunk. Thanks a million for your very detailed answer. Very much indeed, after switching to a proxy (none before that), it immediately worked, i.e., pulled the relevant data. Thanks again for your time, it is much appreciated.
